services:
    frontend:
        build:
            context: .
            dockerfile: dockerfile
        # volumes:
            # - ./:/app
        ports:
            - 80:3000
        tty: true
        # TODO: Change to overlay network for docker swarm & security
        network_mode: host